package cz.muni.fi.pa165.CarRegister.service;

import cz.muni.fi.pa165.CarRegister.entities.User;
import java.util.List;

/**
 * @author Sevo001
 */


public interface UserService {
    
   /* Adds User to the DB 
      @param user to create 
      @return user that has been added to DB */
    User create(User user);
    
    
    /*  Modifies data of an User entry in DB.
        @param user to modify
        @return modified user */
    User update(User user);
    
    
    /* Removes User from DB 
     * @param user to be deleted */
    void delete(User user);
    
    /* Returns all Users from DB
     * @return List<User>   Collection of User objects */
    List<User> findAll(); 
        
    /* Returns specific User identified by his id
     * If no such id in the database, returns null
     * @param id Unique identifier generated by database
     * @return User object with given id or null if no such entry */
    User findById(Long id);
        
    /* Returns specific User identified by his login
     * If no such login in the database, returns null
     * @param login Unique identifier entered by user
     * @return User object with given login or null if no such entry */
    User findByLogin(String login);
    
    boolean authenticate(User u, String password);
        
        
}
